CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;
using System.Data.Entity.Core;
using System.Data.Entity.SqlServer;

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : Controller
    {    // GET: /Medicos/

        private CadeMeuMedicoBDEntities db = new CadeMeuMedicoBDEntities();
 
        public ActionResult Index()
        {
            var medicos = db.Medicos.Include("Cidades").Include("Especialidades").ToList();
            
            return View(medicos);
        }

        public ActionResult Adicionar()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
         
              ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }


       
        [HttpPost]
        public ActionResult Adicionar(Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medicos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade","Nome",medicos.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome",medicos.IDEspecialidade);
            return View(medicos);
        }

    
    }
}

CadeMeuMedico/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cade meu Medico? -@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <style>
        body{
            padding-top: 60px;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Cade meu Medico?</a> 
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li id="menuPaises">
                        @Html.ActionLink("Paises","Index","Paises")
                    </li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Médicos", "Index", "Medicos");
                    </li>
                </ul>
            </div>
        </div>        
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <script src="@Url.Content("~/Scripts/jquery-2.1.3.min.js")">
    </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")">
    </script>
    @RenderSection("script", required:false);

</body>
</html>